spring:
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/products/**
#        - id: user-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/users/**
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/api/orders/**,/api/cart/**
#        - id: eureka-server
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
#          filters:
#            - SetPath=/
#        - id: eureka-server-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

