spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**,/api/cart/**
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

